[project]
name = "xproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "easyocr>=1.7.2",
    "pytesseract>=0.3.10",
    "kmbox-net-rust",
    # "mss>=10.1.0",
    "opencv-python-headless>=4.13.0.92",
    # "setuptools>=82.0.0",
    "torch",
    "torchvision",
    "ultralytics>=8.4.12",
    "rapidocr-onnxruntime>=1.4.4",
    "onnxruntime-directml>=1.24.4; sys_platform == 'win32'",
    "onnxruntime>=1.24.4; sys_platform != 'win32'",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

# [tool.uv.sources]
# torch = { index = "pytorch-cpu" }
# torchvision = { index = "pytorch-cpu" }

[tool.uv]
environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
]

# 镜像仓库
[[tool.uv.index]]
url="https://pypi.tuna.tsinghua.edu.cn/simple"
default=true
